# Generated by Django 2.2.3 on 2019-08-18 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('list_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lists.List')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['list_id'], name='item_list_id_index'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('list_id', 'text')},
        ),
    ]
