# Generated by Django 2.2.3 on 2019-08-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='list_id',
            field=models.IntegerField(default=1),
        ),
    ]
